# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.81.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  lane :bump_version do |options|
    if options[:type] != "major" && options[:type] != "minor" && options[:type] != "patch"
      fail("\n\nPlease specify type of version bump. The valid options are:\n- major\n- minor\n- patch\n\nYou specify the type by adding type:<type> after calling this lane.")
    end
    increment_version_number(bump_type: options[:type])
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Deploy a new version"
  lane :deploy do
    ensure_git_branch(branch: "master")
    scan
    add_git_tag(tag: "v#{get_version_number}")
    push_git_tags
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
